### PR TITLE
Fix crash and rendering where large content is pasted to console on non-Windows

### LINKED ISSUE #663: Exception on non-Windows w/ command line w/ more lines than visible console buffer
Environment data
----------------

```
PS version: 6.0.2
PSReadline version: 2.0.0-beta1
os: Darwin BrianShlettsMBP.attlocal.net 17.4.0 Darwin Kernel Version 17.4.0: Sun Dec 17 09:19:54 PST 2017; root:xnu-4570.41.2~1/RELEASE_X86_64 x86_64
PS file version:
```

Steps to reproduce or exception report
--------------------------------------

This occurred while attempting to paste in the Get-IniContent function at https://gallery.technet.microsoft.com/scriptcenter/ea40c1ef-c856-434b-b8fb-ebd7a76e8d91
```
Last 200 Keys:
 Space Space } Enter
 Space Space Space Space W r i t e - V e r b o s e Space " $ ( $ M y I n v o c a t i o n . M y C o m m a n d . N a m e ) : : Space F i n i s h e d Space P r o c e s s i n g Space f i l e : Space $ F i l e P a t h " Enter
 Space Space Space Space R e t u r n Space $ i n i Enter
 Space Space } Enter
 Enter
 Space Space E n d Enter
 Space Space { Enter
 Space Space Space Space W r i t e - V e r b o s e Space " $ ( $ M y I n v o c a t i o n . M y C o m m a n d . N a m e ) : : Space F u n c t i o n Space e n d e d " Enter
 Space Space } Enter
 } Enter


Exception:
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension.
Parameter name: top
Actual value was -69.
   at System.Console.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.Insert(Char c)
   at Microsoft.PowerShell.PSConsoleReadLine.SelfInsert(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(ConsoleKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics)
```

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
Several issues:

1. When large content is pasted to the console window on Windows, the buffer scrolls and PSReadLine now has a negative value for the cursor.  Exception is raised when trying to set the cursor location to a negative y value.  Fix is to check for this and set y to 0 (top).
2. When the buffer scrolls on paste, the re-rendering gets confused as it didn't track the scrolling appropriately.  Fix is to skip drawing content that is off screen.
3. If the last line drawn to the screen is at the bottom of the screen buffer and the width of the output is exactly the window width, scroll doesn't happen until the next character is drawn; however, PSReadLine expected it to scroll so it's off by one.  Fix here is to catch this and reset position back one line.

Fix https://github.com/lzybkr/PSReadLine/issues/663

### CODE REVIEW

**Comment by lzybkr** [comment]
I think the changes are fine, I'll try them out for a bit before merging.

Are you also going to fix `MenuComplete`? See this [comment](https://github.com/lzybkr/PSReadLine/issues/663#issuecomment-385506238).

**Comment by SteveL-MSFT** [comment]
@lzybkr that's a separate issue (able to repro with a large directory listing with my changes).  I'll look at it in between other work as a separate PR.

**Comment by SteveL-MSFT** [comment]
@lzybkr it comes up easily on non-Windows when pasting a large script

**Comment by lzybkr** [comment]
It happens easily on Windows as well, but you need a small window.

For my education and to better understand an appropriate fix - when are small console windows normally hit on non-Windows? I know that with no gui the window is small, but where else?

**Comment by SteveL-MSFT** [comment]
The default terminal size on Ubuntu is 80x24.

**Comment by lzybkr** [comment]
Maybe it's reasonable to disallow a command line that exceeds the buffer height, at least until you can actually edit it properly.

**Comment by SteveL-MSFT** [comment]
@lzybkr I think we should take this fix as even if you can't edit the buffer, it does show the syntax highlighting correctly making it easier to read.  If you think we should explicitly disallow editing, I think we should have that as a separate issue.  This PR does fix the current issue of an unhandled exception.

**Comment by lzybkr** [comment]
I'm still on the fence about allowing `_initialY` to be negative. Before this PR, there was no code that expected that, this change basically takes the position that it is an expected condition, and we need to carefully review all other uses.

**Comment by SteveL-MSFT** [comment]
There aren't too many references to `_initialY` in the code.  The `menu` code relies on `_initialY` and is probably the related crash for tab-complete for a large result set which I'll look into after we resolve this one.  The alternative requires using a different variable to track how far off the screen we are.

**Comment by lzybkr** [comment]
If we decide a negative `_initialY` is reasonable, the field declaration **and** where we change it should have comments saying as much and why.

**Comment by lzybkr** [comment]
It would be good to add a test as well. The current console proxy does use a fixed buffer, but it might need some improvements to handle this scenario.

**Pull request closed without merging**
