### PR TITLE
Update `HelpInfoURI` for the PSReadLine module

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Update `HelpInfoURI` for the PSReadLine module

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [x] Make sure you've added one or more new tests
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/PowerShell/PSReadLine/pull/1589)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@adityapatwardhan and @sdwheeler The newer version of PSReadLine will be used with downlevel PowerShell as well, such as 6.2, does the URL works in that case?
I tried the latest PSReadLine on 6.2.3 with the new URL, and `Update-Help` brings down the old version help content. But with the same PSReadLine on PS 7.0, `Update-Help` brings down the correct version of help content.

On 6.2.3:
```
PS C:\Users> Update-Help -Module PSReadLine -UICulture en-US -Scope CurrentUser -Force -Verbose
VERBOSE: Resolving URI: "https://aka.ms/powershell71-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.1/"
VERBOSE: Performing the operation "Update-Help" on target "PSReadLine, Current Version: 0.0.0.0, Available Version: 7.0.0.0, UICulture: en-US".
VERBOSE: PSReadLine: Updated C:\Users\dongbow\Documents\PowerShell\Help\PSReadLine\en-US\Microsoft.PowerShell.PSReadLine2.dll-Help.xml. Culture en-US Version 7.0.0.0
VERBOSE: Resolving URI: "https://go.microsoft.com/fwlink/?linkid=2113630"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelp.blob.core.windows.net/powershell/help/7.0/PSReadLine/"
VERBOSE: Performing the operation "Update-Help" on target "PSReadLine, Current Version: 7.0.0.0, Available Version: 7.0.0.0, UICulture: en-US".
VERBOSE: PSReadLine: Updated C:\Users\dongbow\Documents\PowerShell\Help\PSReadLine\en-US\about_PSReadLine.help.txt. Culture en-US Version 7.0.0.0
VERBOSE: PSReadLine: Updated C:\Users\dongbow\Documents\PowerShell\Help\PSReadLine\en-US\Microsoft.PowerShell.PSReadLine2.dll-Help.xml. Culture en-US Version 7.0.0.0
```

On 7.0
```
PS C:\Users> Update-Help -Module PSReadLine -UICulture en-US -Scope CurrentUser -Force -Verbose
VERBOSE: Resolving URI: "https://aka.ms/powershell71-help"
VERBOSE: Your connection has been redirected to the following URI: "https://pshelpprod.blob.core.windows.net/cabinets/powershell-7.1/"
VERBOSE: Performing the operation "Update-Help" on target "PSReadLine, Current Version: 0.0.0.0, Available Version: 7.0.0.0, UICulture: en-US".
VERBOSE: PSReadLine: Updated C:\Users\dongbow\Documents\PowerShell\Help\PSReadLine\en-US\Microsoft.PowerShell.PSReadLine2.dll-Help.xml. Culture en-US Version 7.0.0.0
```

**Comment by sdwheeler** [comment]
@daxian-dbw The intent of the docs has been to document the version of the module that ships with that version of PowerShell. 

- PS6.2.x shipped with PSR2.0-beta. 
- PS7.0 shipped with PSR2.0
- PS7.1 will ship with PSR2.0.x

We have been making changes the the PSR docs in the 7.1 folder branch. So my assumption is that we intend to ship the updated version of PSR in 7.1. If that changes then we need to decide how we want to present the docs.

**Comment by daxian-dbw** [comment]
PSReadLine module works on previous PowerShell versions down to PS 5.0, and it has always been the case.
When a PS 5.1 user installs PSReadLine 2.1, the user should be able to get the correct help content according to that version. If that's not possible with the current way it works, then we need to revisit how to present the docs.

**Comment by sdwheeler** [comment]
What I was talking about had more to do with which docs we publish on the website. When you install a new version of PSReadLine on any version of PowerShell, the HelpInfoURI in the module manifest dictates which version of the help you get. So if Update-Help is not getting the right content then we have a bug.

**Comment by daxian-dbw** [comment]
> When you install a new version of PSReadLine on any version of PowerShell, the HelpInfoURI in the module manifest dictates which version of the help you get. So if Update-Help is not getting the right content then we have a bug.

That's good to know. So with this new help URL, `Update-Help PSReadLine` on downlevel powershell should bring down the latest version of the help content, right? If so, then my observation that it doesn't work on PS 6.2.3 should be a bug.

**Comment by sdwheeler** [comment]
> If so, then my observation that it doesn't work on PS 6.2.3 should be a bug.

Right. But I would try again after a while to see if it is not a cache issue.

**Comment by daxian-dbw** [comment]
@sdwheeler Sure, will do later today.

**Comment by daxian-dbw** [comment]
@sdwheeler I double checked on PS 6.2.3 and `Update-Help` works as expected except for not having the `about_PSReadLine.help.txt` downloaded.
Is there an issue in PowerShell-Docs that is tracking this bug?

**Comment by sdwheeler** [comment]
@daxian-dbw Per our discussion, @theJasonHelmick is tracking this with the DevRel engineering team in our weekly standups.

**Review by sdwheeler — APPROVED** [review]

**Pull request merged**
