### PR TITLE
Add the ability to change Vi cmd mode dispatch tables.

### PR DESCRIPTION
**Pull request by jazzdelightsme**

### CODE REVIEW

**Comment by jazzdelightsme** [comment]
Addresses issue https://github.com/lzybkr/PSReadLine/issues/314.

I don't know what the deal is with the resources... they don't seem to build quite right. But I've included my additional new resource anyway.

**Comment by lzybkr** [comment]
The warning seems fine.
The resources are messed up because I can't figure out how to get Windows build to generate the same file that VS does, so the file matches what I get out of Windows.  It's a pain, I'll figure it out sometime.

**Pull request merged**
