### PR TITLE
Fixes for #571 and #623

### PR DESCRIPTION
**Pull request by srdubya**
I hope this branch is in good enough shape for these fixes to be acceptable.

### CODE REVIEW

**Comment by lzybkr** [comment]
@srdubya - I fixed your branch on GitHub, but I had to force push to get rid of the merge commits, and this means you can't do a simple `git pull` to your local clone without getting into this same state.

Assuming you have no other local work (no branches or commits in master that you didn't push) - then it's probably easiest to delete your local files and clone https://github.com/srdubya/PSReadLine.git again.

In the future, if you run `git pull` and it says it can't fast forward, you need to pull from upstream before committing anything.

Alternatively, you can create a branch, make your fix, and submit the branch for the PR - this should always merge cleanly.

**Comment by srdubya** [comment]
Looked like the changes for 456 were missing, so I added them.

**Comment by lzybkr** [comment]
I think I revisited 456 when fixing something else and replaced your fix. You added a test in #573 which is still there, so I don't think we need the last 4 commits.

**Comment by lzybkr** [comment]
@srdubya - these changes were squashed, so you will need to force push to your master branch to avoid a merge commit.

It's probably easiest to create a branch for each PR and never commit directly to master. If you find yourself using `git merge`, you can use `--ff-only` to avoid merge commits in master - it will reject the merge if you can't fast forward.

**Pull request merged**
