### PR TITLE
Prioritize highlight of command names, prevent bleed from aligned nested tokens

### PR DESCRIPTION
**Pull request by msftrncs**
Referencing #836, 
- Prioritize the selection of the command color when a token is flagged as 'CommandName'. (to handle a parameter token that is flagged as a command name, it is really a command name)  
- Prevent the bleed of a token with nested tokens in to the rest of the statement.

### CODE REVIEW

**Comment by msftrncs** [comment]
I added another commit to complete what can be fixed in #836, where nested tokens would bleed the parent tokens color unto the rest of the statement, if the last nested token ended together with the parent token.  In the case of `& hello$ab -hello`, lets not prioritize command names so much the next item gets the same color.

**Review by daxian-dbw — APPROVED** [review]
Could you please add a test? I'm not sure if it's easy to do so though ...

**Comment by msftrncs** [comment]
I have added a commit that implements two test scenarios, each of which attempts to test for the two items addressed above under slightly different scenarios.

**Comment by msftrncs** [comment]
I force pushed as my previous commit was trying to change (remove) the BOM.

**Review by daxian-dbw — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
