### PR TITLE
Import PowerShell changes

### PR DESCRIPTION
**Pull request by andyleejordan**
Hello,

I exported the changes made to PSReadLine in the PowerShell repo, and imported them here. I've added a commit so that it can be built outside of the PowerShell repo; however, I have not dealt with merge conflicts.

I would advise against attempting to rebase this, as it is too far diverged (I tried; it's not worth it). Merging master in would be the best choice; and the conflicts didn't look too bad (mostly around the addition of the TTY Console abstraction).

All changes were either made by Microsoft employees/contractors, or people who signed the PowerShell CLA.

Issue reference: https://github.com/PowerShell/PowerShell/issues/996

To export and import changes, in the PowerShell repo I did:

``` sh
git format-patch -o ~/patches --relative=src/Microsoft.PowerShell.PSReadLine 3603f2810.. src/Microsoft.PowerShell.PSReadLine
```

(The last argument there may have been unnecessary.)

And to import into PSReadLine, I did:

``` sh
git am --directory=PSReadLine ~/patches/*
```

This procedure can continue to be used to sync patches back and forth, as long as the common base is known (which I obtained by inspecting 3603f2810, the first commit in the PSReadLine subtree). I'm sure there are other ways to go about this, but `format-patch` and `am` are the ones I am most familiar with.

### CODE REVIEW

**Comment by andyleejordan** [comment]
What ended up happening with this?

**Comment by lzybkr** [comment]
I was sort of sitting on this until the story for creating 1 binary for Windows PowerShell and PowerShell core was worked out.

But after that's worked out, there is more work - this PR disables clipboard support because .Net Core doesn't have the apis we use.

**Comment by andyleejordan** [comment]
Okay, cool. I was just going through my PR Dashboard and cleaning stuff up. I had PRs open from 2014...

**Comment by lzybkr** [comment]
I cherry-picked many of the changes and reworked a couple big changes around rendering and key bindings - see #561.

**Pull request closed without merging**
