### PR TITLE
Alternate: Fix IndexOutOfRangeException in GenerateRender

### PR DESCRIPTION
**Pull request by msftrncs**
Offering slightly different, but really the same, fix for #911, along with a test, but with less explanation.

/cc: @daxian-dbw

### CODE REVIEW

**Comment by daxian-dbw** [comment]
I like your changes better. I will update mine to be the same as yours with additional comments and one more test to cover the `NullReferenceException`.

**Comment by daxian-dbw** [comment]
@msftrncs Yes :)

**Comment by msftrncs** [comment]
I almost submitted #989 with a the `break` in it, but thought the EOS would always be there.   I'm mentioning this for reference, as I should have added `break` when adding the `while`, because `token` is made null, and then without a break `token` is used in a reference.  My gut said the `break` was needed, I just couldn't see why immediately.  😃

**Comment by daxian-dbw** [comment]
No worries at all. I didn't realize the `stop early` design for parsing `NamedBlock` until looking at this issue.
I looked into PowerShell code to see if `process xxxx xxx`, `begin xxxx ...` and `end xxx ...` should be fixed to generate tokens in a more expected/friendly way.
It doesn't look like a simple change to make it happen. The design is to stop parsing when `process`, `begin` and `end` don't end up with a valid `NamedBlock`, so tokenizing terminates in the middle as by design in those cases.
Fixing it in PSReadLine makes more sense.

**Comment by daxian-dbw** [comment]
@msftrncs Do you mind taking a look at my updates to #1049?
I took your changes and added additional comments and changed the tests a bit.
I didn't update your branch directly only because it's easier to work in my branch :)

**Comment by daxian-dbw** [comment]
Also, I invited you as a contributor to the PSReadLine repo, would you like to accept it? 😄

**Comment by daxian-dbw** [comment]
Close this one as #1049 has been merged. Thanks @msftrncs!

**Pull request closed without merging**
