### PR TITLE
Clipboard.SetDataObject will throw if not on STA thread

### PR DESCRIPTION
**Pull request by jazzdelightsme**
Depending on runspace configuration, we might not be on an STA thread.
(For instance, one easy way to get into such a state manually is
"powershell.exe -MTA", but of course that's not the only scenario.)

This change just checks the current apartment and marshals to an
appropriate thread if necessary.

### CODE REVIEW

**Comment by lzybkr** [comment]
Thanks for finding this issue, I pushed a different fix that reuses an existing helper for exactly this problem.

**Comment by jazzdelightsme** [comment]
Thank you!

**Pull request closed without merging**
