### PR TITLE
Adding VI edit mode, along with unit tests.

### PR DESCRIPTION
**Pull request by srdubya**
I've been through my list of functionality and everything is working with the exception of 'G' -- move to the specified history line.

### CODE REVIEW

**Comment by mhubers** [comment]
I cannot find  Steve's fork for vi-mode.  I love to try it and hoping for having VI in PSReadline as I have it working notepad++ and VS2013 and the last thing I need in life is at my POWERSHELL command line!  :)  Where do I found this fork or a version of PSReadLine that have VI?

**Comment by lzybkr** [comment]
You need to build it yourself.  Clone the project from: https://github.com/srdubya/PSReadLine and you'll have his fork.

**Comment by gwojan** [comment]
Jason, is there any word on whether or not Steve's code will finally be merged with PSReadLine?

**Comment by lzybkr** [comment]
There is no final word yet, but it is likely.

That said, last I checked, Steve's code is generally good, but not yet shippable.  I had asked some folks to try it out, but I haven't seen any feedback.  Generally, this means people haven't tried it, or if they did, found it more or less unusable and not worth their time to provide feedback.

To set expectations - I don't expect to look at Steve's work until May, I have little free time before then - I have a very exciting vacation coming up (I'm riding a unicycle around a very tall mountain in Nepal) and lots to do beforehand.

**Comment by gwojan** [comment]
Very cool, thanks for the reply. I just recently compiled Steve's code and started using it. So far it works pretty well. :D Where is the best place to report issues?

Your upcoming vacation sounds really fun. My best friend growing up was a big unicycle rider as were his four brothers. The were going to try and ride their unicycles across the five mile length of Michigan's Mackinaw Bridge on Labor Day but the MPs refused to let them. Perhaps it had something to do with the possibility of falling 200 feet to a watery death... ;-)

**Comment by twsouthwick** [comment]
I've been using this fork for a few months and haven't run into any major issues.  I've hit to "crashes" where it spits out the last x characters entered (I might be able to find those if anyone's interested).  The vi commands I wanted are all available (although visual mode doesn't work; not sure if that's possible in powershell...)

**Comment by gwojan** [comment]
It seems like visual mode would be possible if you had gVim installed.

On the other hand I would like a visual selection capability similar to the way gVim handles v|V with the ability to 'copy to' and 'paste from' the system clipboard.

**Comment by srdubya** [comment]
Regarding reporting issues:  If you put "Vi" in the title of a defect I will try to keep my eyes open for them and fix them.

Visual Mode:  I've thought about taking a stab at this, but just haven't found the time.

**Comment by gwojan** [comment]
Steve,

Should we be reporting issues as part of your fork or Jason's original project? I don't see a way to report issues on your fork.

**Comment by lzybkr** [comment]
Greg - it's fine to report issues on the original project.

Steve - visual mode is more or less implemented in Windows mode - e.g. Shift+arrow keys extend the selection - so it might be somewhat easy to implement.

**Comment by Kethku** [comment]
Is there any way to use this pull request in windows 10 which now comes with psreadline? I can't seem to install the module after I built it, and I can't uninstall the version that comes with windows now.

**Comment by Kethku** [comment]
I got it working on my win 7 machine and I love it, I wish I could add it everywhere

**Comment by lzybkr** [comment]
@Devagamster - You can
- Delete the version in $env:ProgramFiles\WindowsPowerShell\Modules\PSReadline\1.1 (must be admin)
- Change $env:PSModulePath (in the registry probably) so that a location you control comes before $env:ProgramFiles\WindowsPowerShell\Modules, and install it in that location.
- Install in $env:ProgramFiles\WindowsPowerShell\Modules\PSReadline\1.2 (a higher version is preferred).

**Comment by Kethku** [comment]
Thank you for the quick response! As PSReadline potentially diverges on github from the one that ships with windows 10, it would make sense to document ways to use a more bleeding edge version like you suggest above. If you like I could create a pull request adding this to the readme?

Unless I completely missed it haha

**Comment by lzybkr** [comment]
@Devagamster - sure.  Be sure to try out what you put in the readme to make sure it works, I may have suggested something that doesn't actually work.

**Comment by Kethku** [comment]
Will do

**Pull request merged**
