### PR TITLE
Improve `RecomputeInitialCoords` to be more robust and handle a couple special cases

### LINKED ISSUE #1456: Restore down then maximizing the Windows Terminal causes PSReadline to misplace the cursor
## Environment

From conhost:
```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.19601.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost
BufferWidth: 248
BufferHeight: 68
```

Additionally, from WT:

```none
PS version: 7.0.0
PSReadline version: 2.0.0
os: 10.0.19601.1000 (WinBuild.160101.0800)
PS file version: 7.0.0.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 120
BufferHeight: 30
```

## Steps to reproduce

See https://github.com/microsoft/terminal/issues/2432 and https://github.com/microsoft/terminal/issues/5254

#### Windows Terminal Repro
1. Open Terminal in full screen
2. Type `ls`
3. unmaximize the window
4. maximize the window
5. type `ls` again and see that ls is not positioned correctly

displaybug

#### Conhost repro
With a plain old conhost:
  - Maximize it
  - Run `ls`
  - Restore down
  - _Change the buffer size to match the window size_
  - Maximize again

## Expected behavior

Text appears at previous cursor line

## Actual behavior

Text appears in blank space. Screenshots of process:

pane-text-1

pane-text-2

pane-text-3

## Notes

I'm moving this here because I'm having a hard time tracing through this from our side, and I figured it'd be easier to get help straight from the experts. From [my own investigation](https://github.com/microsoft/terminal/issues/2432#issuecomment-601196035)

> This issue: [PowerShell/PSReadLine#682](https://github.com/PowerShell/PSReadLine/issues/682)
> and the associated PR: [PowerShell/PSReadLine#694](https://github.com/PowerShell/PSReadLine/pull/694)
> 
> Which pointed me to this function
> [PowerShell/PSReadLine:PSReadLine/Render.cs@`198a643`#L985-L1000](https://github.com/PowerShell/PSReadLine/blob/198a64390e713214df20ef580f7a546b5c3ac1e8/PSReadLine/Render.cs#L985-L1000)
> 
> I can't be sure that's actually it, but that's certainly something to look into.
> 
> Though, reading through that, it looks like `_console.CursorTop` might already be wrong at that point in the call. Looks like that function is just trying to see how many rows the input line takes, then is setting the `_initialY` to be that many rows above the cursor. So I'd think the cursor was already wrong at this point.
> 
> I'll keep digging

### LINKED ISSUE #1884: Resizing windows before `Escape` results in ArgumentOutOfRangeException
### Environment
PSReadLine: 2.0.2
PowerShell: 7.0.3
OS: Microsoft Windows 10.0.19041
Last 200 Keys
```
 LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow LeftArrow RightArrow RightArrow RightArrow Backspace Backspace Backspace Backspace Backspace Backspace Backspace g e t Enter
 UpArrow Escape
```

### Exception
```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

```none
PS version: 7.0.3
PSReadline version: 2.0.2
os: 10.0.19041.1 (WinBuild.160101.0800)
PS file version: 7.0.3.0
HostName: ConsoleHost (Windows Terminal)
BufferWidth: 131
BufferHeight: 29
```

## Exception report

```
System.ArgumentOutOfRangeException: The value must be greater than or equal to zero and less than the console's buffer size in that dimension. (Parameter 'top')
Actual value was 29.
   at System.ConsolePal.SetCursorPosition(Int32 left, Int32 top)
   at Microsoft.PowerShell.PSConsoleReadLine.ReallyRender(RenderData renderData, String defaultColor)
   at Microsoft.PowerShell.PSConsoleReadLine.ForceRender()
   at Microsoft.PowerShell.PSConsoleReadLine.RevertLine(Nullable`1 key, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.ProcessOneKey(PSKeyInfo key, Dictionary`2 dispatchTable, Boolean ignoreIfNoAction, Object arg)
   at Microsoft.PowerShell.PSConsoleReadLine.InputLoop()
   at Microsoft.PowerShell.PSConsoleReadLine.ReadLine(Runspace runspace, EngineIntrinsics engineIntrinsics, CancellationToken cancellationToken)
```

## Steps to reproduce

I was using Powershell to issue a few HTTPie commands, which involved recalling the last command and using `left` and/or `ctrl`+`left` to go back over the last command to slightly edit it. I resized the window (for the purposes of a screen shot) and this issue occured.

[Edited] This issue happens only when you resize the window after `UpArrow` and before `Escape`.

## Expected behavior

No error message

## Actual behavior

The error 
```
Oops, something went wrong.  Please report this bug with the details below.
Report on GitHub: https://github.com/PowerShell/PSReadLine/issues/new?template=Bug_Report.md
```
Along with the details above

### LINKED ISSUE #2954: Black screen after using tui apps, but only when using Set-PSReadLineKeyHandler
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

ezgif com-gif-maker

### Environment data

```console
PS Version: 7.1.5
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.22000.1 (WinBuild.160101.0800)
BufferWidth: 120
BufferHeight: 30
```

### Steps to reproduce

```powershell
#Install fzf (or any other tui app)

fzf # choose an item, it gets printed on the screen and the next prompt appears

Set-PSReadlineKeyHandler -Chord "Shift+Tab" -ScriptBlock {fzf} # Or any key
# Press the the key, select item
# Black screen, after pressing enter the next prompt appears, but the result is never printed

```

### Expected behavior

I expect the behavior when starting the app from the hotkey to be the same as when starting directly - 

When the app quits it prints its result and the next prompt appears.

### Actual behavior

When quitting the app the terminal is a black screen

If the app prints something, like the result in fzf, it never gets displayed.

If you try typing, the text appears on the middle without a prompt:
image

When pressing enter the prompt appears again, but the result never does.

### LINKED ISSUE #2984: Double-cell characters that get wrapped to the next line not removed from the screen when deleting
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
No exception.
```

### Screenshot

Animation

Animation

### Environment data

```console
PS Version: 7.2.0-rc.1
PS HostName: ConsoleHost (Windows Terminal)
PSReadLine Version: 2.1.0
PSReadLine EditMode: Windows
OS: 10.0.19041.1 (WinBuild.160101.0800)
BufferWidth: 91
BufferHeight: 25
```

### Steps to reproduce

1. Make sure the double-cell character wraps to the next line. It means that there is 1 cell buffer left on the current line for the double-cell character, so that character will be rendered to the next line.
2. Start to delete characters, from the end, or from the middle of the line.
3. You will see the double-cell character left behinds even though it's already removed from the buffer.

The GIF's in the screenshot section above are 2 examples.

### Expected behavior

Deletion works as expected to remove the character from screen.

### Actual behavior

The double-cell characters are left on screen, even though the characters were already removed from the text buffer.

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Fix #2984
Fix `PhysicalLineCount` to take into account that double-cell character may get wrapped to the next line when it cannot fit in the current physical line.

Fix #2954
Handle the special case where the screen is cleared by a terminal UI utility in `RecomputeInitialCoords`.

Fix #1884
Improve `RecomputeInitialCoords` by using the old cursor position in the rendered text on screen to calculate the new initial coordinates when there is any change to `_buffer` and `_current`. Before this change, we always depend on `_buffer` and `_current` to re-calculate the new initial coordinates, but `_buffer` and `_current` may have changed when we are doing the re-calculation, for example, `Escape` is pressed to revert line, in which case `_buffer` will be reset and `_current` will be 0. That would result in wrong calculation and exception being thrown.

Fix #1456
Improve `RecomputeInitialCoords` to handle the `max-size => normal-size => max-size` resizing.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [x] Make sure you've added one or more new tests
- [x] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3074)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@andschwa Can you please help to self-host this PSReadLine build? It would be great if it can be used on macOS for a while before we merge this PR, just to make sure it's stable enough.
You can download the zip package from this CI build: https://ci.appveyor.com/project/PowerShell/psreadline/builds/41709712/artifacts

**Comment by andyleejordan** [comment]
@daxian-dbw downloading now!

**Comment by daxian-dbw** [comment]
Thank you @andschwa!

**Comment by daxian-dbw** [comment]
@andschwa Can you please do a review when you have time? Thanks!
BTW, did you run into any issue while using this private build on macOS?

**Comment by andyleejordan** [comment]
@daxian-dbw No issues! But can't say I threw it through the ringer.

**Comment by daxian-dbw** [comment]
@andschwa Any issues you ran into with this private build? Are you fine if I merge this PR?

**Pull request merged**
