### PR TITLE
Tab completion doesn't show files whose names differ from others by case only

### LINKED ISSUE #3455: Tab completion doesn't show files whose names differ from others by case only
### Prerequisites

- [X] Write a descriptive title.
- [X] Make sure you are able to repro it on the [latest released version](https://www.powershellgallery.com/packages/PSReadLine)
- [X] Search the existing issues, especially the pinned issues.

### Exception report

```console
N/A
```

### Screenshot

N/A

### Environment data

```console
PS Version: 7.3.0-preview.7
PS HostName: ConsoleHost
PSReadLine Version: 2.2.6
PSReadLine EditMode: Vi
OS: Linux Cuddles-Berry 5.15.0-1015-raspi #17-Ubuntu SMP PREEMPT Mon Sep 12 13:14:51 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
BufferWidth: 208
BufferHeight: 55
```

### Steps to reproduce

Promoted from https://github.com/PowerShell/PowerShell/issues/14365

Non-Windows filesystems are case-sensitive, and there has been an option `fsutil.exe file queryCaseSensitiveInfo $path enable` to make Windows also case sensitive on per-folder basis (useful for interop, e.g. WSL or checking out repositories with mixed-case files). `PSReadLine` suggestion deduplication logic uses `HashSet<string>(StringComparer.OrdinalIgnoreCase)` which is then a problem when you have files differing only in case.

Repro steps:

```pwsh
$tempdir = "tmp:/$(Get-Random)"
New-Item $tempdir Directory
if ($PSVersionTable.OS -match 'Windows') { fsutil.exe file queryCaseSensitiveInfo $tempdir enable }
New-Item 'TEST', 'test'
# input: ./t<TAB><TAB>
```

### Expected behavior

Suggestions cycle between `./test` and `./TEST`

### Actual behavior

Suggestion shows only one option, usually `./TEST` because it was created earlier, but may by environment

### PR DESCRIPTION
**Pull request by dkaszews**
# PR Summary

Fixes #3455 

Remove case-insensitive comparator from suggestion deduplication logic. Unnecessary `ToArray()` removed in neighboring line to improve performance.

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [ ] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](https://portal.fabricbot.ms/api/codeflow?pullrequest=https://github.com/PowerShell/PSReadLine/pull/3456)

### CODE REVIEW

**Comment by dkaszews** [comment]
Can I get some help with tests? I wrote a quick failing test with `Assert.Equal(true, false);`, but running `./build.ps1 -Test` all I'm getting is:

```
Starting test execution, please wait...
A total of 1 test files matched the specified pattern.
No test matches the given testcase filter `FullyQualifiedName~Test.en_US_Linux`
```

**Comment by daxian-dbw** [comment]
The `ToArray()` cannot be removed without changing how the filtering is done, because you cannot delete items from a collection while enumerating it.

I updated the code to get rid of `ToArray()`, as well as merging this fix with https://github.com/PowerShell/PSReadLine/pull/3454.

**Review by daxian-dbw — APPROVED** [review]
LGTM

**Comment by dkaszews** [comment]
> The ToArray() cannot be removed without changing how the filtering is done, because you cannot delete items from a collection while enumerating it.

Good catch, thanks. There is a better pattern to do it on the fly though:

```cs
for (int i = 0; i < collection.Length; i++) {
    if (predicate(collection[i])) {
        // postdec cancels out increment, so next loop still uses same index
        collection.RemoveAt(i--);
    }
}
```

I personally like it as it's compact and efficient, other people find it hacky. Up to you.

**Pull request merged**
