### PR TITLE
Add GitHub Action to pre-triage new issues

### PR DESCRIPTION
**Pull request by daxian-dbw**
# PR Summary

Add a GitHub Action to pre-triage new issue -- close the issues that are duplicate of #1306 and #1315

## PR Checklist

- [x] PR has a meaningful title
    - Use the present tense and imperative mood when describing your changes
- [x] Summarized changes
- [ ] Make sure you've added one or more new tests
- [ ] Make sure you've tested these changes in terminals that PowerShell is commonly used in (i.e. conhost.exe, Windows Terminal, Visual Studio Code Integrated Terminal, etc.)
- **User-facing changes**
    - [x] Not Applicable
    - **OR**
    - [ ] Documentation needed at [PowerShell-Docs](https://github.com/MicrosoftDocs/PowerShell-Docs)
        - [ ] Doc Issue filed: 

###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/PowerShell/PSReadLine/pull/2117)

### CODE REVIEW

**Comment by iSazonov** [comment]
Bot war! 😄 Need to add auto issue creation in PSReadline 😄

**Comment by iSazonov** [comment]
Hmm, why not? If implement this reporting by telemetry users will do not create useless issues. Workflow would be: PSReadline error -> send a telemetry -> filter the telemetry -> create new issue only if needed.

**Comment by daxian-dbw** [comment]
Nice idea 👍 Most of the duplicate issues are reported against the old versions of PSReadLine, so the bot is still needed. As for your suggestion, the user interaction is still important because repro steps are important for us to really investigate the issue.

**Comment by iSazonov** [comment]
> the user interaction is still important because repro steps are important for us to really investigate the issue.

I'd speculate 95% questions is about _user environment_. I believe it makes sense to enhance the trace error report with the information (terminal, its geometry, font, code page and so on).

As for user interaction, we could add a correlation id in the trace - if an user open new issue manually (copy-paste from screen or share screenshot) you could use the correlation id to search auto report in trace database.

**Pull request merged**
