### PR TITLE
Adding color for prompt text

### PR DESCRIPTION
**Pull request by powercode**
When the promt is drawn with a different
color than the default text, it renders ugly when
we set it back to another color than what was
originally set.
prompt

### CODE REVIEW

**Comment by lzybkr** [comment]
Did you try adding the color to PromptText, like this?

```powershell
Set-PSReadLineOption -PromptText "$e[96m>"
```

**Comment by powercode** [comment]
Ah, clever :)

**Comment by powercode** [comment]
Almost clever :)
That changes the length of the prompt text, so we change color 5 characters behind the prompt text.

**Comment by lzybkr** [comment]
I'm not a fan of excessive options.

What do you think about fixing `PromptText` to ignore color escape sequences? PowerShell does this [here](https://github.com/PowerShell/PowerShell/blob/c1c5344a8897262433141ecbc13bb06ac2c4bbef/src/Microsoft.PowerShell.ConsoleHost/host/msh/ConsoleControl.cs#L2752) - though I think that code doesn't handle CJK correctly - I think this [PR](https://github.com/PowerShell/PowerShell/pull/5739) fixes that.

**Comment by powercode** [comment]
The fewer options the better for sure!
I'll take a look.

**Review by lzybkr — APPROVED** [review]
Thanks for the fix,

I was actually hitting the same issue in my personal admin prompt, but too busy to give it any thought so I appreciate you taking care of it.

**Pull request merged**
