### PR TITLE
Remove MIT License, move License.txt to root, update build script

### PR DESCRIPTION
**Pull request by SteveL-MSFT**
###### Microsoft Reviewers: [Open in CodeFlow](http://wpcp.azurewebsites.net/CodeFlowProtocolProxy2.php?pullrequest=https://github.com/PowerShell/PSReadLine/pull/1452)

### CODE REVIEW

**Comment by daxian-dbw** [comment]
@SteveL-MSFT `License.txt` still has `Copyright (c) 2013, Jason Shirk` as the first line. Should that be changed to `Copyright (c) Microsoft Corporation`?

**Comment by iSazonov** [comment]
Isn't the project now under MIT license?

**Comment by daxian-dbw** [comment]
@iSazonov After consulting with the corporate attorney, it's been decided to keep the original BSD license for PSReadLine.

**Comment by iSazonov** [comment]
@daxian-dbw Thanks! Should we add this ("BSD license") in the file, readme and GitHub repo description explicitly?
Also the PR description could be "Replace MIT license with BSD..."

**Comment by daxian-dbw** [comment]
I need to confirm with @joeyaiello on whether I should refresh all files with a new header that calls out the BSD license. As for the repo itself, the readme.md already calls out the license, at the end.

**Comment by iSazonov** [comment]
Also MSFT could want to preserve Jason's copyright and add MSFT copyright.

**Review by daxian-dbw — APPROVED** [review]
Updated the PR to resolve conflicts.
I will go merging this PR. If we need to update the license.txt I will submit a new PR.

**Pull request merged**
