### PR TITLE
Fixes for #605, #606

### PR DESCRIPTION
**Pull request by MVKozlov**
Added processing of possible errors. Maybe it's too much?

### CODE REVIEW

**Comment by lzybkr** [comment]
@MVKozlov - thanks for the PR, it made it obvious what the problem was. I didn't see any real problems with your change, but I do want to minimize allocations.

I went ahead and made my own fix if you'd like to give it a try - see #611.

**Comment by MVKozlov** [comment]
I think it is really better deal with allocations but I do not understand reasons why you don't `Console.Write(s.Substring(from, i - from)); ` before `while (!done && j < s.Length) ` as I do :)

In any way we have a couple of `action()` without any `Write` inside them, so write can be moved out of the cycle

**Comment by lzybkr** [comment]
I've already had complaints about performance of the old implementation that was similar, so even though the code is simpler allocating many substrings, I'll stick with the better performing code.

Spans would be helpful here, but I don't want to ship another dll just for this.

I was optimizing for a scenario that really shouldn't happen, so I switched to your way, it's slightly cleaner I guess, but I went and made it less clean to correctly handle partially invalid sequences.

**Comment by lzybkr** [comment]
I took your change for #606 and my own (with your suggestions) for #605, so I'm closing this PR.

**Pull request closed without merging**
