### PR TITLE
Fix init for non-US keyboards

### LINKED ISSUE #614: Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
Environment data
----------------
```powershell
& {
    "PS version: $($PSVersionTable.PSVersion)"
    "PSReadline version: $((Get-Module PSReadline).Version)"
    if ($IsLinux -or $IsOSX) {
        "os: $(uname -a)"
    } else {
        "os: $((dir $env:SystemRoot\System32\cmd.exe).VersionInfo.FileVersion)"
    }
    "PS file version: $((dir $pshome\pwsh.exe).VersionInfo.FileVersion)"
}
```
```
PS version: 6.0.0-rc.2
PSReadline version: 2.0.0
os: 6.1.7601.17514 (win7sp1_rtm.101119-1850)
PS file version: 6.0.0
```
```powershell
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      6.0.0-rc.2
PSEdition                      Core
GitCommitId                    v6.0.0-rc.2
OS                             Microsoft Windows 6.1.7601 S
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0, 5.0, 5.1.10032.0, 6.0.0-rc.2}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Steps to reproduce or exception report
--------------------------------------
```powershell
Get-PSReadLineOption
```
```
Get-PSReadLineOption : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineOption
+ ~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineOption], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetPSReadLineOption
```
```powershell
Get-PSReadLineKeyHandler
```
```
Get-PSReadLineKeyHandler : The type initializer for 'Microsoft.PowerShell.PSConsoleReadLine' threw an exception.
At line:1 char:1
+ Get-PSReadLineKeyHandler
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Get-PSReadLineKeyHandler], TypeInitializationException
+ FullyQualifiedErrorId : System.TypeInitializationException,Microsoft.PowerShell.GetKeyHandlerCommand
```
note : the  issue template dont reference 'pwsh.exe'

### PR DESCRIPTION
**Pull request by lzybkr**
Fix #614

### CODE REVIEW

**Comment by jeanga** [comment]
With the release of RS5, non US users for PSReadLine badly need an official release with this fix.
Thanks!

**Comment by lzybkr** [comment]
@jeanga - Hopefully @SteveL-MSFT can make that happen.

**Comment by SteveL-MSFT** [comment]
@jeanga, @lzybkr I think after the UTF8 OutputEncoding PR gets merged, it makes sense to have another beta release

**Comment by Thdub** [comment]
Also hope to see beta4 soon!

**Comment by gcollic** [comment]
Is there any official release coming soon with this fix ? Windows Update broke my shell, not really happy about it :-(

**Comment by lzybkr** [comment]
@gcollic - I'm aiming to get another release out before the end of the year. This is strictly a spare (personal) time project for me so it does take a bit longer.

**Pull request merged**
